name: weview
description: "weview"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  webview_flutter: ^3.0.4
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.12.0
  firebase_auth: ^4.17.4
  cupertino_icons: ^1.0.8
  kakao_map_flutter: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
